#!/usr/bin/env bash
for n in $(cat tests/test00)
do
  for q in  1 2 3 5 7 11 15485773 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97
  do
    x=$(bc <<< "$n % $q")
    if [ $x -eq 0 ];
    then
      p=$(bc <<< "$n/$q")
      echo "$n=$p*$q"
      break
    fi
  done
done
