#!/usr/bin/python3
import sys


def is_prime(n):
    if n % 2 == 0:
        return False
    for i in range(3, n // 2, 2):
        if n % i == 0:
            return False
    return True

with open(sys.argv[1], 'r') as f:
    for num in f.read().split():
        num = int(num)
        if num % 2 == 0:
            if is_prime(num // 2):
                print("{}={}*{}".format(num, 2, num // 2))
        else: 
            for divisors in range(3, num // 2, 2):
                if num % divisors == 0:
                    if is_prime(divisors) and is_prime(num // divisors):
                        print("{}={}*{}".format(num, divisors, num // divisors))
                        break
